name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set PAT
        env:
          TOKEN: ${{ secrets.PUBLIC_TOKEN }}
        run: |
          git remote add public https://x-access-token:$TOKEN@github.com/yxt5276/test-public.git

      - name : pushhh
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --force public HEAD:main
